### ISSUE TITLE
Psort won't run: LoweringError type mismatch

### ISSUE THREAD

**Issue by DradeAW** [esedaghatnejad/psort#3]
Hi,

I wanted to try out Psort, but I am unable to run it.

I downloaded the latest version, and installed it in a `miniconda 3` environment using `python 3.8.8` (I'm on Ubuntu 20.04).
Now when I run `psort` or `python -m psort`, I have the following error message:

```
(psort) wyngaard@nspc05:~/dev/Psort/psort$ python -m psort
Traceback (most recent call last):
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/errors.py", line 744, in new_error_context
    yield
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 328, in lower_inst
    self.storevar(val, inst.target.name)
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 1278, in storevar
    raise AssertionError(msg)
AssertionError: Storing i64 to ptr of i32 ('dim'). FE type int32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/nsr/wyngaard/.conda/envs/psort/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/users/nsr/wyngaard/.conda/envs/psort/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/export/home1/users/nsr/wyngaard/dev/Psort/psort/psort/__main__.py", line 10, in <module>
    from .gui.signals import PsortGuiSignals
  File "/export/home1/users/nsr/wyngaard/dev/Psort/psort/psort/gui/signals.py", line 21, in <module>
    from psort.utils import lib
  File "/export/home1/users/nsr/wyngaard/dev/Psort/psort/psort/utils/lib.py", line 576, in <module>
    from psort.dependencies.umap_package import UMAP
  File "/export/home1/users/nsr/wyngaard/dev/Psort/psort/psort/dependencies/umap_package/__init__.py", line 1, in <module>
    from .umap_ import UMAP
  File "/export/home1/users/nsr/wyngaard/dev/Psort/psort/psort/dependencies/umap_package/umap_.py", line 54, in <module>
    from .layouts import (
  File "/export/home1/users/nsr/wyngaard/dev/Psort/psort/psort/dependencies/umap_package/layouts.py", line 39, in <module>
    def rdist(x, y):
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/decorators.py", line 221, in wrapper
    disp.compile(sig)
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 909, in compile
    cres = self._compiler.compile(args, return_type)
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 79, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 93, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 106, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 606, in compile_extra
    return pipeline.compile_extra(func)
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 353, in compile_extra
    return self._compile_bytecode()
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 415, in _compile_bytecode
    return self._compile_core()
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 395, in _compile_core
    raise e
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 386, in _compile_core
    pm.run(self.state)
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 339, in run
    raise patched_exception
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/typed_passes.py", line 463, in run_pass
    NativeLowering().run_pass(state)
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/typed_passes.py", line 384, in run_pass
    lower.lower()
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 136, in lower
    self.lower_normal_function(self.fndesc)
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 190, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 216, in lower_function_body
    self.lower_block(block)
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/users/nsr/wyngaard/.conda/envs/psort/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/numba/core/errors.py", line 751, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Storing i64 to ptr of i32 ('dim'). FE type int32

File "psort/dependencies/umap_package/layouts.py", line 52:
def rdist(x, y):
    <source elided>
    result = 0.0
    dim = x.shape[0]
    ^

During: lowering "dim = static_getitem(value=$8load_attr.2, index=0, index_var=$const10.3, fn=<built-in function getitem>)" at /export/home1/users/nsr/wyngaard/dev/Psort/psort/psort/dependencies/umap_package/layouts.py (52)
```

Did I do something wrong in the installation?

Thanks,
Aurélien

**Comment by esedaghatnejad** [comment]
No.
I got the same error yesterday! I updated my Anaconda over the weekend. Apparently the new Numba package is not compatible with the old UMAP package.
Here is something similar. Not exactly the same error.
https://github.com/lmcinnes/umap/issues/371

**Comment by esedaghatnejad** [comment]
There are two possible solutions, (1) installing an older version of the Anaconda package, I suggest anaconda 2020.02 with Python 3.7
(2) pip install the newest version of the umap_learn and then change the psort/utils/lib.py line 576
from psort.dependencies.umap_package import UMAP

**Comment by esedaghatnejad** [comment]
I will work on my end and let you know what works for me.

**Comment by DradeAW** [comment]
> There are two possible solutions, (1) installing an older version of the Anaconda package, I suggest anaconda 2020.02 with Python 3.7
> (2) pip install the newest version of the umap_learn and then change the psort/utils/lib.py line 576
> from psort.dependencies.umap_package import UMAP

Ah yes!
Changing the line to `from umap import UMAP` did the trick!

Thank you :)

**Comment by esedaghatnejad** [comment]
Great. Thanks for the feedback.
