### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by ludo67100** [esedaghatnejad/psort#9]
Hi, I'm prompted with the following error when trying to start psort after installation: 

>  (psort) C:\Users\ludovic\anaconda3>psort
> \\?\C:\Users\ludovic\anaconda3\envs\psort\Scripts\psort-script.py:15: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
>   from pkg_resources import load_entry_point
> Traceback (most recent call last):
>   File "\\?\C:\Users\ludovic\anaconda3\envs\psort\Scripts\psort-script.py", line 33, in <module>
>     sys.exit(load_entry_point('psort==1.0.8', 'console_scripts', 'psort')())
>   File "C:\Users\ludovic\anaconda3\envs\psort\lib\site-packages\pkg_resources\__init__.py", line 536, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "C:\Users\ludovic\anaconda3\envs\psort\lib\site-packages\pkg_resources\__init__.py", line 2931, in load_entry_point
>     return ep.load()
>   File "C:\Users\ludovic\anaconda3\envs\psort\lib\site-packages\pkg_resources\__init__.py", line 2518, in load
>     return self.resolve()
>   File "C:\Users\ludovic\anaconda3\envs\psort\lib\site-packages\pkg_resources\__init__.py", line 2524, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "C:\Users\ludovic\anaconda3\envs\psort\lib\site-packages\psort-1.0.8-py3.7.egg\psort\__main__.py", line 10, in <module>
>     from .gui.signals import PsortGuiSignals
>   File "C:\Users\ludovic\anaconda3\envs\psort\lib\site-packages\psort-1.0.8-py3.7.egg\psort\gui\signals.py", line 21, in <module>
>     from psort.utils import lib
>   File "C:\Users\ludovic\anaconda3\envs\psort\lib\site-packages\psort-1.0.8-py3.7.egg\psort\utils\lib.py", line 21, in <module>
>     import matplotlib as plt
>   File "C:\Users\ludovic\anaconda3\envs\psort\lib\site-packages\matplotlib\__init__.py", line 109, in <module>
>     from . import _api, _version, cbook, docstring, rcsetup
>   File "C:\Users\ludovic\anaconda3\envs\psort\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
>     from matplotlib.colors import Colormap, is_color_like
>   File "C:\Users\ludovic\anaconda3\envs\psort\lib\site-packages\matplotlib\colors.py", line 51, in <module>
>     from PIL import Image
>   File "C:\Users\ludovic\anaconda3\envs\psort\lib\site-packages\PIL\Image.py", line 100, in <module>
>     from . import _imaging as core
> ImportError: DLL load failed: The specified module could not be found.

**Comment by ludo67100** [comment]
EDIT: fixed the issue by updating Pillow using pip 

`(psort) C:\Users\ludovic\anaconda3>pip install -U Pillow`
